# Site settings
title: Graham Griffiths
email: contact@grahamrgriffiths.com
description: > # this means to ignore newlines until "baseurl:"
  A new place to hold my blog posts and projects, work in progress
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.grahamrgriffiths.com" # the base hostname & protocol for your site
twitter_username: grahamgriffiths
github_username:  grahamrgriffiths
linkedin_username: grahamrgriffiths
flickr_username: grahamrgriffiths

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title
