# Site settings
title: Graham Griffiths Blog
email: contact@grahamrgriffiths.com
description: > # this means to ignore newlines until "baseurl:"
  A new place to hold my blog posts and projects, work in progress
baseurl: "" # the subpath of your site, e.g. /blog/
imgUrl: {{"/img/" | prepend: site.baseurl | prepend: site.url}}
url: "http://blog.grahamrgriffiths.com" # the base hostname & protocol for your site
twitter_username: grahamgriffiths
github_username:  grahamrgriffiths

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title
