# Site settings
title: Graham Griffiths
email: contact@grahamrgriffiths.com
description: > # this means to ignore newlines until "baseurl:"
  A place to hold my personal website, any blog posts and projects. Work in progress.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.grahamrgriffiths.com" # the base hostname & protocol for your site
twitter_username: grahamgriffiths
github_username:  grahamrgriffiths
linkedin_username: grahamrgriffiths
flickr_username: grahamrgriffiths
microsoft_username: grahamgriffiths
meetup_username: 94129412
mastodon_username: @grahamgriffiths

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title
